apiVersion: v1
kind: ReplicationController
metadata:
  name: rethinkdb-proxy
  labels:
    app: rethinkdb-proxy
spec:
  replicas: 1
  selector:
    app: rethinkdb-proxy
  template:
    metadata:
      labels:
        app: rethinkdb-proxy
    spec:
      containers:
      - name: rethinkdb-proxy
        image: openstf/ambassador:latest
        env:
        - name: RETHINKDB_PORT_28015_TCP
          value: "tcp://<rethinkdb-host>:28015"
        ports:
        - containerPort: 28015
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 256Mi
          
