apiVersion: v1
kind: Service
metadata:
  labels:
    app: stf-triproxy-app
  name: stf-triproxy-app
spec:
  ports:
   - port: 7150
     targetPort: 7150
   - port: 7160
     targetPort: 7160
   - port: 7170
     targetPort: 7170
  selector:
    app: stf-triproxy-app
