apiVersion: v1
kind: Pod
metadata:
  labels:
    db: rethinkdb
    role: admin
  name: rethinkdb-admin
spec:
  containers:
  - image: dimasaryoprakoso/rethinkdb:2.3
    name: rethinkdb
    env:
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    ports:
    - containerPort: 8080
      name: admin-port
    - containerPort: 28015
      name: driver-port
    - containerPort: 29015
      name: cluster-port
    resources:
      limits:
        cpu: 100m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 256Mi
    volumeMounts:
    - mountPath: /data/rethinkdb_data
      name: rethinkdb-storage
  volumes:
  - name: rethinkdb-storage
    emptyDir: {}
