apiVersion: v1
kind: ReplicationController
metadata:
  name: stf-auth
  labels:
    app: stf-auth
spec:
  replicas: 1
  selector:
    app: stf-auth
  template:
    metadata:
      labels:
        app: stf-auth
    spec:
      containers:
      - name: stf-auth
        image: dimasaryoprakoso/stf:latest
        command: ["stf"]
        args: 
        - auth-mock
        - --secret
        - "YOUR SECRET HERE"
        - --port
        - "3000"
        - --app-url
        - "http://stf.example.org/"
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
