apiVersion: v1
kind: ReplicationController
metadata:
  name: stf-auth
  labels:
    app: stf-auth
spec:
  replicas: 1
  selector:
    app: stf-auth
  template:
    metadata:
      labels:
        app: stf-auth
    spec:
      containers:
      - name: stf-auth
        image: dimasaryoprakoso/stf:latest
        command: ["stf"]
        args: 
        - auth-google-oauth2
        - --secret
        - "YOUR SECRET HERE"
        - --port
        - "3000"
        - --app-url
        - "http://stf.example.org/"
        env:
        - name: OAUTH_CLIENT_ID
          value: "YOUR OAUTH CLIENT ID"
        - name: OAUTH_CLIENT_SECRET
          value: "YOUR OAUTH CLIENT SECRET"
        - name: OAUTH_CALLBACK_URL
          value: "YOUR OAUTH CALLBACK URL"
        - name: OAUTH_SCOPE
          value: "openid email"
        - name: OAUTH_HD
          value: "YOUR RESTRICTED DOMAIN (OPTIONAL)"
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 100m
            memory: 256Mi

