apiVersion: v1
kind: Service
metadata:
  labels:
    app: stf-triproxy-dev
  name: stf-triproxy-dev
spec:
  ports:
   - port: 7250
     targetPort: 7250
   - port: 7260
     targetPort: 7260
   - port: 7270
     targetPort: 7270
  selector:
    app: stf-triproxy-dev
