apiVersion: v1
kind: ReplicationController
metadata:
  name: stf-nginx
  labels:
    app: stf-nginx
spec:
  replicas: 1
  selector:
    app: stf-nginx
  template:
    metadata:
      labels:
        app: stf-nginx
    spec:
      containers:
      - name: stf-nginx
        image: dimasaryoprakoso/stf-nginx:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          
