apiVersion: v1
kind: ReplicationController
metadata:
  name: stf-reaper
  labels:
    app: stf-reaper
spec:
  replicas: 1
  selector:
    app: stf-reaper
  template:
    metadata:
      labels:
        app: stf-reaper
    spec:
      containers:
      - name: stf-reaper
        image: dimasaryoprakoso/stf:latest
        command: ["stf"]
        args: 
        - reaper
        - "dev"
        - --connect-push
        - "tcp://stf-triproxy-dev:7270"
        - --connect-sub
        - "tcp://stf-triproxy-app:7150"
        - --heartbeat-timeout
        -  "30000"
        env:
        - name: RETHINKDB_PORT_28015_TCP
          value: "tcp://rethinkdb-proxy:28015"
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          
