apiVersion: v1
kind: ReplicationController
metadata:
  name: stf-websocket
  labels:
    app: stf-websocket
spec:
  replicas: 1
  selector:
    app: stf-websocket
  template:
    metadata:
      labels:
        app: stf-websocket
    spec:
      containers:
      - name: stf-websocket
        image: dimasaryoprakoso/stf:latest
        command: ["stf"]
        args: 
        - websocket
        - --secret
        - "YOUR SECRET HERE"
        - --port
        - "3000"
        - --storage-url
        - "http://stf.example.org"
        - --connect-sub
        - "tcp://stf-triproxy-app:7150"
        - --connect-push
        - "tcp://stf-triproxy-app:7170"
        env:
        - name: RETHINKDB_PORT_28015_TCP
          value: "tcp://rethinkdb-proxy:28015"
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          
